// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Tray.proto

package com.sdj3.dataServerSDJ3.protobuf.TrayProtobuf;

public final class Tray {
  private Tray() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateTrayMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateTrayMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReturnMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReturnMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReturnTrayMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReturnTrayMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nTray.proto\"4\n\021CreateTrayMessage\022\014\n\004nam" +
      "e\030\001 \001(\t\022\021\n\tmaxWeight\030\002 \001(\005\" \n\rReturnMess" +
      "age\022\017\n\007message\030\001 \001(\t\"@\n\021ReturnTrayMessag" +
      "e\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\021\n\tmaxWeight" +
      "\030\003 \001(\0052?\n\013TrayService\0220\n\ncreateTray\022\022.Cr" +
      "eateTrayMessage\032\016.ReturnMessageB1\n-com.s" +
      "dj3.dataServerSDJ3.protobuf.TrayProtobuf" +
      "P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_CreateTrayMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CreateTrayMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateTrayMessage_descriptor,
        new java.lang.String[] { "Name", "MaxWeight", });
    internal_static_ReturnMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ReturnMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReturnMessage_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_ReturnTrayMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ReturnTrayMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReturnTrayMessage_descriptor,
        new java.lang.String[] { "Id", "Name", "MaxWeight", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
