// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Animal.proto

package com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf;

/**
 * Protobuf type {@code ListAnimals}
 */
public final class ListAnimals extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ListAnimals)
    ListAnimalsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListAnimals.newBuilder() to construct.
  private ListAnimals(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListAnimals() {
    animalMessage_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ListAnimals();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ListAnimals(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              animalMessage_ = new java.util.ArrayList<com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.AnimalMessage>();
              mutable_bitField0_ |= 0x00000001;
            }
            animalMessage_.add(
                input.readMessage(com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.AnimalMessage.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        animalMessage_ = java.util.Collections.unmodifiableList(animalMessage_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.Animal.internal_static_ListAnimals_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.Animal.internal_static_ListAnimals_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.ListAnimals.class, com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.ListAnimals.Builder.class);
  }

  public static final int ANIMALMESSAGE_FIELD_NUMBER = 1;
  private java.util.List<com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.AnimalMessage> animalMessage_;
  /**
   * <code>repeated .AnimalMessage animalMessage = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.AnimalMessage> getAnimalMessageList() {
    return animalMessage_;
  }
  /**
   * <code>repeated .AnimalMessage animalMessage = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.AnimalMessageOrBuilder> 
      getAnimalMessageOrBuilderList() {
    return animalMessage_;
  }
  /**
   * <code>repeated .AnimalMessage animalMessage = 1;</code>
   */
  @java.lang.Override
  public int getAnimalMessageCount() {
    return animalMessage_.size();
  }
  /**
   * <code>repeated .AnimalMessage animalMessage = 1;</code>
   */
  @java.lang.Override
  public com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.AnimalMessage getAnimalMessage(int index) {
    return animalMessage_.get(index);
  }
  /**
   * <code>repeated .AnimalMessage animalMessage = 1;</code>
   */
  @java.lang.Override
  public com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.AnimalMessageOrBuilder getAnimalMessageOrBuilder(
      int index) {
    return animalMessage_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < animalMessage_.size(); i++) {
      output.writeMessage(1, animalMessage_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < animalMessage_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, animalMessage_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.ListAnimals)) {
      return super.equals(obj);
    }
    com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.ListAnimals other = (com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.ListAnimals) obj;

    if (!getAnimalMessageList()
        .equals(other.getAnimalMessageList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getAnimalMessageCount() > 0) {
      hash = (37 * hash) + ANIMALMESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getAnimalMessageList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.ListAnimals parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.ListAnimals parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.ListAnimals parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.ListAnimals parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.ListAnimals parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.ListAnimals parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.ListAnimals parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.ListAnimals parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.ListAnimals parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.ListAnimals parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.ListAnimals parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.ListAnimals parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.ListAnimals prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ListAnimals}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ListAnimals)
      com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.ListAnimalsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.Animal.internal_static_ListAnimals_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.Animal.internal_static_ListAnimals_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.ListAnimals.class, com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.ListAnimals.Builder.class);
    }

    // Construct using com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.ListAnimals.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAnimalMessageFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (animalMessageBuilder_ == null) {
        animalMessage_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        animalMessageBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.Animal.internal_static_ListAnimals_descriptor;
    }

    @java.lang.Override
    public com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.ListAnimals getDefaultInstanceForType() {
      return com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.ListAnimals.getDefaultInstance();
    }

    @java.lang.Override
    public com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.ListAnimals build() {
      com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.ListAnimals result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.ListAnimals buildPartial() {
      com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.ListAnimals result = new com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.ListAnimals(this);
      int from_bitField0_ = bitField0_;
      if (animalMessageBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          animalMessage_ = java.util.Collections.unmodifiableList(animalMessage_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.animalMessage_ = animalMessage_;
      } else {
        result.animalMessage_ = animalMessageBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.ListAnimals) {
        return mergeFrom((com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.ListAnimals)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.ListAnimals other) {
      if (other == com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.ListAnimals.getDefaultInstance()) return this;
      if (animalMessageBuilder_ == null) {
        if (!other.animalMessage_.isEmpty()) {
          if (animalMessage_.isEmpty()) {
            animalMessage_ = other.animalMessage_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAnimalMessageIsMutable();
            animalMessage_.addAll(other.animalMessage_);
          }
          onChanged();
        }
      } else {
        if (!other.animalMessage_.isEmpty()) {
          if (animalMessageBuilder_.isEmpty()) {
            animalMessageBuilder_.dispose();
            animalMessageBuilder_ = null;
            animalMessage_ = other.animalMessage_;
            bitField0_ = (bitField0_ & ~0x00000001);
            animalMessageBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAnimalMessageFieldBuilder() : null;
          } else {
            animalMessageBuilder_.addAllMessages(other.animalMessage_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.ListAnimals parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.ListAnimals) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.AnimalMessage> animalMessage_ =
      java.util.Collections.emptyList();
    private void ensureAnimalMessageIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        animalMessage_ = new java.util.ArrayList<com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.AnimalMessage>(animalMessage_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.AnimalMessage, com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.AnimalMessage.Builder, com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.AnimalMessageOrBuilder> animalMessageBuilder_;

    /**
     * <code>repeated .AnimalMessage animalMessage = 1;</code>
     */
    public java.util.List<com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.AnimalMessage> getAnimalMessageList() {
      if (animalMessageBuilder_ == null) {
        return java.util.Collections.unmodifiableList(animalMessage_);
      } else {
        return animalMessageBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .AnimalMessage animalMessage = 1;</code>
     */
    public int getAnimalMessageCount() {
      if (animalMessageBuilder_ == null) {
        return animalMessage_.size();
      } else {
        return animalMessageBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .AnimalMessage animalMessage = 1;</code>
     */
    public com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.AnimalMessage getAnimalMessage(int index) {
      if (animalMessageBuilder_ == null) {
        return animalMessage_.get(index);
      } else {
        return animalMessageBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .AnimalMessage animalMessage = 1;</code>
     */
    public Builder setAnimalMessage(
        int index, com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.AnimalMessage value) {
      if (animalMessageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAnimalMessageIsMutable();
        animalMessage_.set(index, value);
        onChanged();
      } else {
        animalMessageBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .AnimalMessage animalMessage = 1;</code>
     */
    public Builder setAnimalMessage(
        int index, com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.AnimalMessage.Builder builderForValue) {
      if (animalMessageBuilder_ == null) {
        ensureAnimalMessageIsMutable();
        animalMessage_.set(index, builderForValue.build());
        onChanged();
      } else {
        animalMessageBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .AnimalMessage animalMessage = 1;</code>
     */
    public Builder addAnimalMessage(com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.AnimalMessage value) {
      if (animalMessageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAnimalMessageIsMutable();
        animalMessage_.add(value);
        onChanged();
      } else {
        animalMessageBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .AnimalMessage animalMessage = 1;</code>
     */
    public Builder addAnimalMessage(
        int index, com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.AnimalMessage value) {
      if (animalMessageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAnimalMessageIsMutable();
        animalMessage_.add(index, value);
        onChanged();
      } else {
        animalMessageBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .AnimalMessage animalMessage = 1;</code>
     */
    public Builder addAnimalMessage(
        com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.AnimalMessage.Builder builderForValue) {
      if (animalMessageBuilder_ == null) {
        ensureAnimalMessageIsMutable();
        animalMessage_.add(builderForValue.build());
        onChanged();
      } else {
        animalMessageBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .AnimalMessage animalMessage = 1;</code>
     */
    public Builder addAnimalMessage(
        int index, com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.AnimalMessage.Builder builderForValue) {
      if (animalMessageBuilder_ == null) {
        ensureAnimalMessageIsMutable();
        animalMessage_.add(index, builderForValue.build());
        onChanged();
      } else {
        animalMessageBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .AnimalMessage animalMessage = 1;</code>
     */
    public Builder addAllAnimalMessage(
        java.lang.Iterable<? extends com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.AnimalMessage> values) {
      if (animalMessageBuilder_ == null) {
        ensureAnimalMessageIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, animalMessage_);
        onChanged();
      } else {
        animalMessageBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .AnimalMessage animalMessage = 1;</code>
     */
    public Builder clearAnimalMessage() {
      if (animalMessageBuilder_ == null) {
        animalMessage_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        animalMessageBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .AnimalMessage animalMessage = 1;</code>
     */
    public Builder removeAnimalMessage(int index) {
      if (animalMessageBuilder_ == null) {
        ensureAnimalMessageIsMutable();
        animalMessage_.remove(index);
        onChanged();
      } else {
        animalMessageBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .AnimalMessage animalMessage = 1;</code>
     */
    public com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.AnimalMessage.Builder getAnimalMessageBuilder(
        int index) {
      return getAnimalMessageFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .AnimalMessage animalMessage = 1;</code>
     */
    public com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.AnimalMessageOrBuilder getAnimalMessageOrBuilder(
        int index) {
      if (animalMessageBuilder_ == null) {
        return animalMessage_.get(index);  } else {
        return animalMessageBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .AnimalMessage animalMessage = 1;</code>
     */
    public java.util.List<? extends com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.AnimalMessageOrBuilder> 
         getAnimalMessageOrBuilderList() {
      if (animalMessageBuilder_ != null) {
        return animalMessageBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(animalMessage_);
      }
    }
    /**
     * <code>repeated .AnimalMessage animalMessage = 1;</code>
     */
    public com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.AnimalMessage.Builder addAnimalMessageBuilder() {
      return getAnimalMessageFieldBuilder().addBuilder(
          com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.AnimalMessage.getDefaultInstance());
    }
    /**
     * <code>repeated .AnimalMessage animalMessage = 1;</code>
     */
    public com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.AnimalMessage.Builder addAnimalMessageBuilder(
        int index) {
      return getAnimalMessageFieldBuilder().addBuilder(
          index, com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.AnimalMessage.getDefaultInstance());
    }
    /**
     * <code>repeated .AnimalMessage animalMessage = 1;</code>
     */
    public java.util.List<com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.AnimalMessage.Builder> 
         getAnimalMessageBuilderList() {
      return getAnimalMessageFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.AnimalMessage, com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.AnimalMessage.Builder, com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.AnimalMessageOrBuilder> 
        getAnimalMessageFieldBuilder() {
      if (animalMessageBuilder_ == null) {
        animalMessageBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.AnimalMessage, com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.AnimalMessage.Builder, com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.AnimalMessageOrBuilder>(
                animalMessage_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        animalMessage_ = null;
      }
      return animalMessageBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ListAnimals)
  }

  // @@protoc_insertion_point(class_scope:ListAnimals)
  private static final com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.ListAnimals DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.ListAnimals();
  }

  public static com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.ListAnimals getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListAnimals>
      PARSER = new com.google.protobuf.AbstractParser<ListAnimals>() {
    @java.lang.Override
    public ListAnimals parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ListAnimals(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ListAnimals> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListAnimals> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.ListAnimals getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

