// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Animal.proto

package com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf;

public interface ProductMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProductMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>double weight = 3;</code>
   * @return The weight.
   */
  double getWeight();
}
