// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Product.proto

package com.sdj3.slaughterhousesdj3.protobuf.productProtobuf;

public interface ListProductOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ListProduct)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .ProductMessage ProductMessage = 1;</code>
   */
  java.util.List<com.sdj3.slaughterhousesdj3.protobuf.productProtobuf.ProductMessage> 
      getProductMessageList();
  /**
   * <code>repeated .ProductMessage ProductMessage = 1;</code>
   */
  com.sdj3.slaughterhousesdj3.protobuf.productProtobuf.ProductMessage getProductMessage(int index);
  /**
   * <code>repeated .ProductMessage ProductMessage = 1;</code>
   */
  int getProductMessageCount();
  /**
   * <code>repeated .ProductMessage ProductMessage = 1;</code>
   */
  java.util.List<? extends com.sdj3.slaughterhousesdj3.protobuf.productProtobuf.ProductMessageOrBuilder> 
      getProductMessageOrBuilderList();
  /**
   * <code>repeated .ProductMessage ProductMessage = 1;</code>
   */
  com.sdj3.slaughterhousesdj3.protobuf.productProtobuf.ProductMessageOrBuilder getProductMessageOrBuilder(
      int index);
}
