// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Animal.proto

package com.sdj3.dataServerSDJ3.protobuf.animalProtobuf;

public interface AnimalMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AnimalMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string origen = 2;</code>
   * @return The origen.
   */
  java.lang.String getOrigen();
  /**
   * <code>string origen = 2;</code>
   * @return The bytes for origen.
   */
  com.google.protobuf.ByteString
      getOrigenBytes();

  /**
   * <code>double weight = 3;</code>
   * @return The weight.
   */
  double getWeight();

  /**
   * <code>string arrivedDate = 4;</code>
   * @return The arrivedDate.
   */
  java.lang.String getArrivedDate();
  /**
   * <code>string arrivedDate = 4;</code>
   * @return The bytes for arrivedDate.
   */
  com.google.protobuf.ByteString
      getArrivedDateBytes();
}
