// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Animal.proto

package com.sdj3.dataServerSDJ3.protobuf.animalProtobuf;

public final class Animal {
  private Animal() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AnimalIdMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AnimalIdMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProductMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProductMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AnimalMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AnimalMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RegisterAnimalMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RegisterAnimalMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmptyMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmptyMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ListAnimals_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ListAnimals_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Animal.proto\"\035\n\017AnimalIdMessage\022\n\n\002id\030" +
      "\001 \001(\005\":\n\016ProductMessage\022\n\n\002id\030\001 \001(\005\022\014\n\004n" +
      "ame\030\002 \001(\t\022\016\n\006weight\030\003 \001(\001\"P\n\rAnimalMessa" +
      "ge\022\n\n\002id\030\001 \001(\005\022\016\n\006origen\030\002 \001(\t\022\016\n\006weight" +
      "\030\003 \001(\001\022\023\n\013arrivedDate\030\004 \001(\t\"L\n\025RegisterA" +
      "nimalMessage\022\016\n\006origen\030\001 \001(\t\022\016\n\006weight\030\002" +
      " \001(\001\022\023\n\013arrivedDate\030\003 \001(\t\"\016\n\014EmptyMessag" +
      "e\"4\n\013ListAnimals\022%\n\ranimalMessage\030\001 \003(\0132" +
      "\016.AnimalMessage2\341\001\n\rAnimalService\0225\n\024get" +
      "AnimalFromProduct\022\017.ProductMessage\032\014.Lis" +
      "tAnimals\022,\n\rgetAllAnimals\022\r.EmptyMessage" +
      "\032\014.ListAnimals\0221\n\rgetAnimalById\022\020.Animal" +
      "IdMessage\032\016.AnimalMessage\0228\n\016registerAni" +
      "mal\022\026.RegisterAnimalMessage\032\016.AnimalMess" +
      "ageB3\n/com.sdj3.dataServerSDJ3.protobuf." +
      "animalProtobufP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_AnimalIdMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AnimalIdMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AnimalIdMessage_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_ProductMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ProductMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProductMessage_descriptor,
        new java.lang.String[] { "Id", "Name", "Weight", });
    internal_static_AnimalMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_AnimalMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AnimalMessage_descriptor,
        new java.lang.String[] { "Id", "Origen", "Weight", "ArrivedDate", });
    internal_static_RegisterAnimalMessage_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_RegisterAnimalMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RegisterAnimalMessage_descriptor,
        new java.lang.String[] { "Origen", "Weight", "ArrivedDate", });
    internal_static_EmptyMessage_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_EmptyMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmptyMessage_descriptor,
        new java.lang.String[] { });
    internal_static_ListAnimals_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_ListAnimals_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ListAnimals_descriptor,
        new java.lang.String[] { "AnimalMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
