// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Animal.proto

package com.sdj3.dataServerSDJ3.protobuf.animalProtobuf;

public interface EmptyMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EmptyMessage)
    com.google.protobuf.MessageOrBuilder {
}
