// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Animal.proto

package com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf;

public interface ListAnimalsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ListAnimals)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .AnimalMessage animalMessage = 1;</code>
   */
  java.util.List<com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.AnimalMessage> 
      getAnimalMessageList();
  /**
   * <code>repeated .AnimalMessage animalMessage = 1;</code>
   */
  com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.AnimalMessage getAnimalMessage(int index);
  /**
   * <code>repeated .AnimalMessage animalMessage = 1;</code>
   */
  int getAnimalMessageCount();
  /**
   * <code>repeated .AnimalMessage animalMessage = 1;</code>
   */
  java.util.List<? extends com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.AnimalMessageOrBuilder> 
      getAnimalMessageOrBuilderList();
  /**
   * <code>repeated .AnimalMessage animalMessage = 1;</code>
   */
  com.sdj3.slaughterhousesdj3.protobuf.animalProtobuf.AnimalMessageOrBuilder getAnimalMessageOrBuilder(
      int index);
}
