// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Part.proto

package com.sdj3.dataServerSDJ3.protobuf.partProtobuf;

public interface AddPartMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AddPartMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>double weight = 3;</code>
   * @return The weight.
   */
  double getWeight();

  /**
   * <code>int32 animalId = 4;</code>
   * @return The animalId.
   */
  int getAnimalId();

  /**
   * <code>int32 trayId = 5;</code>
   * @return The trayId.
   */
  int getTrayId();
}
